/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perimeters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Perimeters */
        get: operations["list_perimeters_api_perimeters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perimeters/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Perimeter */
        get: operations["get_perimeter_api_perimeters__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{perimeter}/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample Contract */
        get: operations["get_sample_contract_api_samples__perimeter__contracts__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AmountOut */
        AmountOut: {
            /** Value */
            value: string;
            /** Display */
            display: string;
        };
        /** CalculationOut */
        CalculationOut: {
            /** Perimeter */
            perimeter: string;
            /** Month */
            month: string;
            /** Lines */
            lines: components["schemas"]["CommissionLineOut"][];
            /** Exclusions */
            exclusions: components["schemas"]["ExclusionOut"][];
            totals: components["schemas"]["TotalsOut"];
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallTrace"][];
            /**
             * Citations
             * @description Règles citées dans la réponse ou appliquées par le moteur
             */
            citations: components["schemas"]["CitationOut"][];
            /**
             * Unverified Amounts
             * @description Montants cités par l'assistant qui ne proviennent d'aucune source (outil, règles, question)
             */
            unverified_amounts: string[];
            /**
             * Unknown Rules
             * @description Identifiants de règle cités qui n'existent pas
             */
            unknown_rules: string[];
            /**
             * Unknown Products
             * @description Noms de produits cités qui n'existent pas dans le catalogue
             */
            unknown_products: string[];
            /** Model */
            model: string;
        };
        /** CitationOut */
        CitationOut: {
            /** Rule Id */
            rule_id: string;
            /** Label */
            label: string;
            /**
             * In Answer
             * @description L'identifiant de la règle figure dans le texte de la réponse
             */
            in_answer: boolean;
            /**
             * From Calculation
             * @description La règle a été appliquée par le moteur dans un résultat d'outil
             */
            from_calculation: boolean;
        };
        /** CommissionLineOut */
        CommissionLineOut: {
            /** Contract Id */
            contract_id: string;
            /** Product */
            product: string;
            /**
             * Commission Type
             * @enum {string}
             */
            commission_type: "P" | "RP" | "L";
            /** Commission Label */
            commission_label: string;
            /** Amount */
            amount: string;
            /** Amount Display */
            amount_display: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Label */
            rule_label: string;
            /** Formula */
            formula: string;
            /** Rate Source */
            rate_source: string;
        };
        /** ContractInput */
        ContractInput: {
            /**
             * Product
             * @description Code produit, ex. NS-CONFORT
             */
            product: string;
            /**
             * State
             * @description AFN, SEF ou RES (libellés des assureurs acceptés)
             */
            state: string;
            /**
             * Subscription Date
             * Format: date
             */
            subscription_date: string;
            /**
             * Effective Date
             * Format: date
             */
            effective_date: string;
            /**
             * Annual Premium
             * @description Prime annuelle hors taxes, en euros
             */
            annual_premium: number | string;
            /** End Date */
            end_date?: string | null;
            /**
             * Guarantee
             * @default
             */
            guarantee?: string;
            /**
             * Segment
             * @default
             */
            segment?: string;
            /**
             * File Rate Year 1
             * @description Taux transmis par l'assureur
             */
            file_rate_year_1?: number | string | null;
            /**
             * Contract Id
             * @default SIMULATION
             */
            contract_id?: string;
        };
        /** ContractRecordOut */
        ContractRecordOut: {
            /** Contract Id */
            contract_id: string;
            /** Product */
            product: string;
            /** State */
            state: string;
            /**
             * Subscription Date
             * Format: date
             */
            subscription_date: string;
            /**
             * Effective Date
             * Format: date
             */
            effective_date: string;
            /** Annual Premium */
            annual_premium: string;
            /** End Date */
            end_date: string | null;
            /** Guarantee */
            guarantee: string;
            /** Segment */
            segment: string;
            /** File Rate Year 1 */
            file_rate_year_1: string | null;
        };
        /** ExclusionOut */
        ExclusionOut: {
            /** Contract Id */
            contract_id: string;
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Chat Enabled */
            chat_enabled: boolean;
            /** Model */
            model: string | null;
        };
        /** LinearPolicyOut */
        LinearPolicyOut: {
            /** Excluded Movement Prefixes */
            excluded_movement_prefixes: string[];
            /** Excluded Premium Types */
            excluded_premium_types: string[];
            /** Excluded Products */
            excluded_products: string[];
            /** First Year Filter */
            first_year_filter: boolean;
        };
        /** PerimeterDetailsOut */
        PerimeterDetailsOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Insurer */
            insurer: string;
            /** Line Of Business */
            line_of_business: string;
            /** Active */
            active: boolean;
            /** Key Strategy */
            key_strategy: string;
            /** Key Strategy Label */
            key_strategy_label: string;
            /** Exposure Base */
            exposure_base: string;
            /** Exposure Base Label */
            exposure_base_label: string;
            /** Rate Source */
            rate_source: string;
            /** Rate Source Label */
            rate_source_label: string;
            /** Tariff Regularisation */
            tariff_regularisation: boolean;
            /** Seniority Months */
            seniority_months: number | null;
            /** Old Contract Threshold Years */
            old_contract_threshold_years: string;
            /** Max Future Effect Months */
            max_future_effect_months: number | null;
            /** Rate Overrides */
            rate_overrides: components["schemas"]["RateOverrideOut"][];
            /** Product Rules */
            product_rules: components["schemas"]["ProductRuleOut"][];
            linear: components["schemas"]["LinearPolicyOut"];
            /** Products */
            products: components["schemas"]["ProductOut"][];
        };
        /** PerimeterSummaryOut */
        PerimeterSummaryOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Insurer */
            insurer: string;
            /** Line Of Business */
            line_of_business: string;
            /** Active */
            active: boolean;
        };
        /** PremiumRecordOut */
        PremiumRecordOut: {
            /** Contract Id */
            contract_id: string;
            /** Product */
            product: string;
            /**
             * Subscription Date
             * Format: date
             */
            subscription_date: string;
            /**
             * Effective Date
             * Format: date
             */
            effective_date: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Amount Excl Tax */
            amount_excl_tax: string;
            /** Movement */
            movement: string;
            /** Premium Type */
            premium_type: string;
        };
        /**
         * PreviousMonthInput
         * @description Situation du même contrat le mois précédent : seuls l'état, la prime et la date de fin peuvent différer.
         */
        PreviousMonthInput: {
            /** State */
            state: string;
            /** Annual Premium */
            annual_premium?: number | string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ProductOut */
        ProductOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Year 1 */
            year_1: components["schemas"]["RateWindowOut"][];
            /** Year 2 Plus */
            year_2_plus: components["schemas"]["RateWindowOut"][];
        };
        /** ProductRuleOut */
        ProductRuleOut: {
            /** Contract Prefix */
            contract_prefix: string;
            /** Product */
            product: string;
            /** Reason */
            reason: string;
        };
        /** RateOverrideOut */
        RateOverrideOut: {
            /** Rate */
            rate: string;
            /** Display */
            display: string;
            /** Reason */
            reason: string;
            /** Product */
            product: string | null;
            /** Guarantee */
            guarantee: string | null;
            /** Segment */
            segment: string | null;
        };
        /** RateWindowOut */
        RateWindowOut: {
            /** Rate */
            rate: string;
            /** Display */
            display: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** End */
            end: string | null;
        };
        /** SampleContractOut */
        SampleContractOut: {
            /** Perimeter */
            perimeter: string;
            /** Month */
            month: string;
            /** Previous Month */
            previous_month: string;
            /** Contract Id */
            contract_id: string;
            /** Previous Records */
            previous_records: components["schemas"]["ContractRecordOut"][];
            /** Current Records */
            current_records: components["schemas"]["ContractRecordOut"][];
            /** Premiums */
            premiums: components["schemas"]["PremiumRecordOut"][];
            /** Lines */
            lines: components["schemas"]["CommissionLineOut"][];
            /** Exclusions */
            exclusions: components["schemas"]["ExclusionOut"][];
        };
        /** SimulationRequest */
        SimulationRequest: {
            /** Perimeter */
            perimeter: string;
            /**
             * Month
             * @description Mois de calcul, AAAA-MM
             */
            month: string;
            contract: components["schemas"]["ContractInput"];
            previous_month?: components["schemas"]["PreviousMonthInput"] | null;
        };
        /** ToolCallTrace */
        ToolCallTrace: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Ok */
            ok: boolean;
        };
        /** TotalsOut */
        TotalsOut: {
            precompte: components["schemas"]["AmountOut"];
            reprises: components["schemas"]["AmountOut"];
            lineaire: components["schemas"]["AmountOut"];
            net: components["schemas"]["AmountOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_perimeters_api_perimeters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerimeterSummaryOut"][];
                };
            };
        };
    };
    get_perimeter_api_perimeters__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerimeterDetailsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_contract_api_samples__perimeter__contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                perimeter: string;
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Limite de débit de la démo atteinte (en-tête Retry-After) ou quota du fournisseur de modèle épuisé */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /**
             * @description Flux Server-Sent Events. Événements, dans l'ordre où ils surviennent :
             *
             *     - `delta` `{"text"}` : texte généré. Le texte qui précède des appels d'outils n'est pas la réponse finale.
             *     - `tool_call` `{"name", "arguments"}` : un outil va être exécuté.
             *     - `tool_result` : trace de l'appel (même format que `tool_calls` de `/api/chat`).
             *     - `done` : réponse complète, au même format que `/api/chat`.
             *     - `error` `{"status", "detail"}` : échec du modèle (429 quota épuisé, 502 indisponible) ; le flux s'arrête.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Limite de débit de la démo atteinte (en-tête Retry-After) ou quota du fournisseur de modèle épuisé */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
